name: dinacaruso
favicon: null
layout_spectrum: 0.7561292503960431
typography_spectrum: 0.04792350227944553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.07216053083539009
  lightness: 0.036593944765627384
  saturation: 0.7479475971776992
  rhythmicContrast: 0.369411903899163
purpose: []
