title: dinacaruso
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7479475971776992
  brandStrength: 0.07216053083539009
  rhythmicContrast: 0.369411903899163
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.03659394476562738
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: dinacaruso
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3064516
layout_spectrum: 0.7383512
